- hosts: localhost
  vars:
   host:  "34.209.118.204"
   username: "admin"
   password: "r3dh4t1!"
   vdom: "root"
  
  tasks:
  - name: Set static route on the fortigate
    fortiosconfig:
     action: "set"
     host:  "{{  host }}"  
     username: "{{  username}}"  
     password: "{{ password }}"  
     vdom:  "{{  vdom }}"  
     config: "router static"
     https: False
     ssl_verify: False
     config_parameters:
       seq-num: "8"
       dst: "10.10.32.0 255.255.255.0"
       device: "port1"
       gateway: "192.168.40.252"
  - name:   firewall policy
    fortiosconfig:
     config: "firewall policy"
     action: "set"
     host:  "{{ host }}"  
     username: "{{ username }}"  
     password: "{{ password }}"  
     vdom:  "{{  vdom }}"
     https: False
     ssl_verify: False
     config_parameters:
        policyid: "2"
        name: "ansible"
        json:
          policyid: "2"
          name: "Created By Ansible"
          action: "accept"
          srcintf: [ {"name": "port1"} ] 
          dstintf: [{"name":"port1"} ]
          srcaddr: [{"name":"all"} ] 
          dstaddr: [{"name":"all"}] 
          schedule: "always" 
          service:  [{"name":"HTTP"}]
          logtraffic: "all"  
  - name: system resource
    fortiosconfig:
     config: "system vdom-resource select"
     action: "get"
     host:  "{{ host }}"
     username: "{{ username }}"  
     password: "{{ password }}"
     vdom: "global"
     https: False
     ssl_verify: False
  - name: Get information
    fortiosconfig:
     config: "system global"
     action: "get"
     host:  "{{ host }}"  
     username: "{{ username }}"  
     password: "{{ password }}"
     vdom: "global"
     https: False
     ssl_verify: False
     config_parameters:
       name: "global"

